"""initial

Revision ID: 91c4a53eec32
Revises: 
Create Date: 2026-06-28 12:25:20.070154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91c4a53eec32'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.Enum('USER_APPROVED', 'USER_REJECTED', 'USER_SUSPENDED', 'USER_CANCELLED', 'POST_DELETED', 'REPORT_DECIDED', 'PROFESSIONAL_ADDED', 'PROFESSIONAL_UPDATED', 'MODERATOR_ASSIGNED', 'DATA_EXPORTED', 'USER_LOGIN', 'USER_LOGOUT', name='auditaction'), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=256), nullable=True),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=512), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ADMIN', 'MODERATOR', 'PROFESSIONAL', name='userrole'), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('user_type', sa.Enum('WIDOWER', 'WIDOW', 'ORPHAN_MALE', 'ORPHAN_FEMALE', name='usertype'), nullable=True),
    sa.Column('sector', sa.Enum('HASIDIC', 'LITVISH', 'SEPHARDIC', 'GENERAL', name='sector'), nullable=True),
    sa.Column('id_number', sa.String(length=512), nullable=True),
    sa.Column('phone', sa.String(length=512), nullable=True),
    sa.Column('face_image_url', sa.String(length=1024), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('account_status', sa.Enum('PENDING_OTP', 'PENDING_APPROVAL', 'PARTIALLY_APPROVED', 'ACTIVE', 'REJECTED', 'SUSPENDED', 'CANCELLED', name='accountstatus'), nullable=False),
    sa.Column('otp_code', sa.String(length=10), nullable=True),
    sa.Column('otp_expires_at', sa.DateTime(), nullable=True),
    sa.Column('first_approver_id', sa.String(length=36), nullable=True),
    sa.Column('second_approver_id', sa.String(length=36), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('moderator_cells', sa.JSON(), nullable=True),
    sa.Column('alert_email', sa.String(length=256), nullable=True),
    sa.Column('professional_domain', sa.Enum('LAWYER', 'ACCOUNTANT', 'PSYCHOLOGIST', 'FINANCIAL_ADVISOR', 'RABBI', 'MEDICINE', 'SOCIAL_WORKER', 'OTHER', name='professionaldomain'), nullable=True),
    sa.Column('professional_groups', sa.JSON(), nullable=True),
    sa.Column('professional_sectors', sa.JSON(), nullable=True),
    sa.Column('professional_description', sa.Text(), nullable=True),
    sa.Column('is_active_professional', sa.Boolean(), nullable=False),
    sa.Column('is_suspended', sa.Boolean(), nullable=False),
    sa.Column('suspended_until', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['first_approver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['second_approver_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('direct_messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('sender_id', sa.String(length=36), nullable=False),
    sa.Column('recipient_id', sa.String(length=36), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('doc_type', sa.Enum('DEATH_CERTIFICATE', 'SELFIE', 'ID_CARD', 'PASSPORT', name='documenttype'), nullable=False),
    sa.Column('storage_url', sa.String(length=1024), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_on', sa.Date(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('forum_posts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('author_id', sa.String(length=36), nullable=False),
    sa.Column('group_visibility', sa.Enum('WIDOWERS', 'WIDOWS', 'ORPHANS_MALE', 'ORPHANS_FEMALE', 'ALL', name='groupvisibility'), nullable=False),
    sa.Column('sector_visibility', sa.Enum('HASIDIC', 'LITVISH', 'SEPHARDIC', 'GENERAL', 'ALL', name='sectorvisibility'), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('attachment_url', sa.String(length=1024), nullable=True),
    sa.Column('status', sa.Enum('VISIBLE', 'HIDDEN', 'DELETED', name='poststatus'), nullable=False),
    sa.Column('report_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('professional_queries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('asker_id', sa.String(length=36), nullable=False),
    sa.Column('professional_id', sa.String(length=36), nullable=True),
    sa.Column('domain', sa.Enum('LAWYER', 'ACCOUNTANT', 'PSYCHOLOGIST', 'FINANCIAL_ADVISOR', 'RABBI', 'MEDICINE', 'SOCIAL_WORKER', 'OTHER', name='professionaldomain'), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'ANSWERED', 'CLOSED', name='querystatus'), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('show_real_name', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('answered_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asker_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['professional_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('reporter_id', sa.String(length=36), nullable=False),
    sa.Column('target_type', sa.Enum('FORUM_POST', 'DIRECT_MESSAGE', 'PROFESSIONAL_QUERY', name='reporttargettype'), nullable=False),
    sa.Column('target_id', sa.String(length=36), nullable=False),
    sa.Column('reported_user_id', sa.String(length=36), nullable=False),
    sa.Column('reason', sa.Enum('HARASSMENT', 'OFFENSIVE', 'SPAM', 'OTHER', name='reportreason'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('decision', sa.Enum('PENDING', 'INVALID', 'VALID', name='reportdecision'), nullable=False),
    sa.Column('moderator_id', sa.String(length=36), nullable=True),
    sa.Column('moderator_note', sa.Text(), nullable=True),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['moderator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reported_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reports')
    op.drop_table('professional_queries')
    op.drop_table('forum_posts')
    op.drop_table('documents')
    op.drop_table('direct_messages')
    op.drop_table('users')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
